version: '3.3'
services:
  node:
    env_file:
      - ./src/.env
    container_name: project_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm i && npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my_network
  mongo:
    container_name: project_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
